spring:
  mail:
    host: smtp.163.com
    username: 
    password: 
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video_sites_api
    username: root
    password: 

file:
  upload:
    allowPicTypes:
      - image/jpeg
      - image/png
      - image/jpg
      - image/bmp
    allowVideoTypes:
      - video/mp4
      - video/webm
      - video/x-msvideo
      - video/quicktime
      - video/x-matroska
      - video/x-flv
      - video/x-ms-wmv
      - video/mpeg
      - video/3gpp
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
